#!/bin/bash

#背景画像
ln -nfs /usr/share/backgrounds/paper-town/background-1.jpg /etc/alternatives/desktop-background

#BodhiBuilderのアイコンの変更
ln -nfs /usr/share/pixmaps/paper-town/paper-town.png /usr/share/icons/bbinstall.png
ln -nfs /usr/share/pixmaps/paper-town/paper-town.png /usr/share/icons/bbinstall_previous.png
